<a href="https://colab.research.google.com/github/chacha715/graduate/blob/main/242STG21_assignment2b.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Scientific Programming in Python - Dictionaries and Functions

### Problem 1. Library, with dictionaries

We’ll revisit the Problem 3 of Assignment 2, where we had to manipulate some data from a fake
library.

In this problem, we had the following format for the data:


In [1]:
[[123456,312314,531337],                     # Student IDS
 ['John Doe',' Jane Miller','Ted Johnson'],  # Student Names
 [1.49,0.00,8.12]]                           # Amounts owed

[[123456, 312314, 531337],
 ['John Doe', ' Jane Miller', 'Ted Johnson'],
 [1.49, 0.0, 8.12]]

>**(a)** Construct a dictionary to store this data, using the student ID (the ﬁrst big number) as the **key**, and the amount owed as the **values**.

> Use the code below to get you started. You can type the key, value pairs into the curly brackets `{ }`.

In [3]:
student_id_to_amount_owed = {123456: 1.49, 312314: 0.00, 531337: 8.12}  # complete this line to include all the student IDs and amounts owed
print(student_id_to_amount_owed)

{123456: 1.49, 312314: 0.0, 531337: 8.12}


> **(b)** Use this dictionary to find out how much money the student with id `531337` owes.

> You should use square brackets `[ ]` to index into your dictionary.


In [4]:
student_id_to_amount_owed[531337]

8.12

> Try also finding out how much 123456 owes. What about newly enrolled student 999888?

In [5]:
amount_owed_by_531337 = student_id_to_amount_owed[531337]
print(amount_owed_by_531337)

8.12


> **(c)** Create another dictionary which maps the name of the student to its student id.  This time, instead of typing the values in by hand, fill in this dictionary by looping over the list `student_names_and_ids` given below:


In [10]:
student_names_and_ids = [('John Doe', 123456), ('Jane Miller', 312314), ('Ted Johnson', 531337)]

studentname_to_id = {}  # initialise empty dictionary

# write code here to populate the dictionary
for nameID in student_names_and_ids:
  studentname_to_id[nameID[0]] = int(nameID[1])

print(studentname_to_id)
# desired output : {'Jane Miller': 312314, 'John Doe': 123456, 'Ted Johnson': 531337}

{'John Doe': 123456, 'Jane Miller': 312314, 'Ted Johnson': 531337}



> **(c)** Print how much money 'John Doe' owes the library, using both of your dictionaries.

>  *(Hint: First find out John Doe's student ID, then use this to find out how much he owes)*

In [12]:
John_doe_balance = student_id_to_amount_owed[studentname_to_id['John Doe']]
print(John_doe_balance)

1.49


> **(d)** Create the list of the names of students owing more than £1.0 to the library.

> *(Hint: If it is easier, first make a list of all the student IDs which owe more than £1.0 Then adapt the code to create a list of names instead).*


In [13]:
bad_students = [] # type answer here

for name in studentname_to_id:
  ID = studentname_to_id[name]
  if student_id_to_amount_owed[ID] > 1.0:
    bad_students.append(name)

print(bad_students)

['John Doe', 'Ted Johnson']


###Problem 2. Counting words

>**(a)** In this problem we’ll use the text of Alice in Wonderland to construct dictionaries counting the
number of times particular words and pairs of words appear.

In [14]:
from google.colab import drive
drive.mount('/content/drive')

import os
os.chdir('/content/drive/MyDrive/석사/data') # working directory를 설정

Mounted at /content/drive


In [ ]:
# assignment2에서 이미 생성함

# import urllib.request
# URL = "http://www.gutenberg.org/files/11/11.txt"
# f = urllib.request.urlopen(URL)
# open("alice.txt","wb").write(f.read())

This will create a new file called "alice.txt"

>**(b)** We'll process alice.txt in loops like this:

In [49]:
f = open("alice_edited.txt", "r")

# your code here (1)
words = {}

for line in f.readlines():
  for word in line.strip().split():

    # your code here (2)
    if word not in words:
      words[word] = 1
    else:
      words[word] += 1

# your code here (3)
print(words)

{"ALICE'S": 3, 'ADVENTURES': 1, 'IN': 2, 'WONDERLAND': 1, 'Lewis': 1, 'Carroll': 1, 'THE': 9, 'MILLENNIUM': 1, 'FULCRUM': 1, 'EDITION': 1, '3.0': 1, 'CHAPTER': 12, 'I.': 1, 'Down': 1, 'the': 1507, 'Rabbit-Hole': 1, 'Alice': 221, 'was': 328, 'beginning': 11, 'to': 703, 'get': 43, 'very': 126, 'tired': 7, 'of': 490, 'sitting': 10, 'by': 53, 'her': 203, 'sister': 5, 'on': 138, 'bank,': 2, 'and': 714, 'having': 10, 'nothing': 22, 'do:': 1, 'once': 18, 'or': 68, 'twice': 1, 'she': 484, 'had': 175, 'peeped': 3, 'into': 67, 'book': 3, 'reading,': 1, 'but': 101, 'it': 346, 'no': 64, 'pictures': 4, 'conversations': 1, 'in': 344, 'it,': 38, "'and": 38, 'what': 85, 'is': 63, 'use': 16, 'a': 606, "book,'": 2, 'thought': 63, "'without": 1, "conversations?'": 1, 'So': 23, 'considering': 3, 'own': 9, 'mind': 4, '(as': 2, 'well': 27, 'as': 237, 'could,': 7, 'for': 125, 'hot': 4, 'day': 11, 'made': 29, 'feel': 8, 'sleepy': 3, 'stupid),': 1, 'whether': 11, 'pleasure': 2, 'making': 8, 'daisy-chain': 1, '

>Modify this code so that it creates a new dictionary called words at (1).<br> For (2), if a word
is not already in the dictionary words, then add it to the dictionary with a value of 1. <br>If a
word is already in the dictionary words, then increment the value stored in the dictionary
by one.<br>

>At location (3), print out the dictionary words.

>**(b)** How many times does the word “the” appear? What about the word “The”?

In [50]:
# code here
print(words['the'], words['The'])

1507 89


>**(d)** Modify the code so words are counted independent of whether they are made of upper or
lower case letters. i.e., “the”, “The” and “tHE” are all treated as the same word.


In [48]:
# code here
f = open("alice_edited.txt", "r")

words_lower = {}

for line in f.readlines():
  for word in line.strip().split():
    word_lower = word.lower()
    if word_lower not in words_lower:
      words_lower[word_lower] = 1
    else:
      words_lower[word_lower] += 1

print(words_lower)

{"alice's": 11, 'adventures': 4, 'in': 351, 'wonderland': 2, 'lewis': 1, 'carroll': 1, 'the': 1605, 'millennium': 1, 'fulcrum': 1, 'edition': 1, '3.0': 1, 'chapter': 12, 'i.': 1, 'down': 78, 'rabbit-hole': 3, 'alice': 221, 'was': 333, 'beginning': 11, 'to': 706, 'get': 43, 'very': 139, 'tired': 7, 'of': 493, 'sitting': 10, 'by': 56, 'her': 208, 'sister': 5, 'on': 142, 'bank,': 2, 'and': 766, 'having': 10, 'nothing': 22, 'do:': 1, 'once': 19, 'or': 68, 'twice': 1, 'she': 518, 'had': 176, 'peeped': 3, 'into': 67, 'book': 3, 'reading,': 1, 'but': 116, 'it': 362, 'no': 67, 'pictures': 4, 'conversations': 1, 'it,': 38, "'and": 55, 'what': 91, 'is': 71, 'use': 16, 'a': 614, "book,'": 2, 'thought': 63, "'without": 1, "conversations?'": 1, 'so': 126, 'considering': 3, 'own': 9, 'mind': 5, '(as': 3, 'well': 27, 'as': 249, 'could,': 7, 'for': 135, 'hot': 4, 'day': 11, 'made': 29, 'feel': 8, 'sleepy': 3, 'stupid),': 1, 'whether': 11, 'pleasure': 2, 'making': 8, 'daisy-chain': 1, 'would': 76, 'be'

>**(e)** Repeat the previous exercise, but instead of counting the number of times a word appears,
count the number of times pairs of words appear. You might ﬁnd it useful to store the
previous word in a variable.

In [52]:
# code here
print(words_lower['the']) # The pair of “the”, “The” and “tHE”are included in counting 'the' in words_lower dictionary.

1605


>**(f)** What are the most common words and pairs of words in Alice in Wonderland?<br> You might find the *sorted* function or the *sort* function for lists to be useful.


In [55]:
# hint: example of how you use sorted
x = [1,4,2,7,5,6,3]
print(x)
print(sorted(x),type(sorted(x))) # outputs a list
# print(sort(x),type(sort(x)))  # outputs a numpy.ndarray

[1, 4, 2, 7, 5, 6, 3]
[1, 2, 3, 4, 5, 6, 7] <class 'list'>


In [62]:
sorted_words_by_counts = sorted(words.items(), key=lambda x:x[1])
print(sorted_words_by_counts[-1]) # 첫 dictionary에서 가장 흔한 단어는 1507번 사용된 'the'이다.

('the', 1507)


In [65]:
sorted_words_lower_by_pairs = sorted(words_lower.items(), key=lambda x:x[1])
print(sorted_words_lower_by_pairs[-1]) # 두 번째 dictionary에서 가장 흔한 페어는 1605번 사용된 'the' 페어이다.

('the', 1605)


### Problem 4. ArgMax and ArgSort

>**(a)** Finding the index of the largest (or smallest) element in a list is a commonly needed opera-
tion, but Python does not provide this function in its standard library (numpy will provide those). Write two functions


In [66]:
def argmax(list_input):
  idx = None
  for i, item in enumerate(list_input):
    if i== 0:
      m = item
    elif item > m:
      idx = i
      m = item
  return idx

def argmin(list_input):
  idx = None
  for i, item in enumerate(list_input):
    if i== 0:
      m = item
    elif item < m:
      idx = i
      m = item
  return idx

>that return the index of the largest and smallest element in the list *list_input* respectively. Example output:


    >>> list1 = [1,3,2,6,0,2,3,4,5]
    >>> argmax(list1)
    3
    >>> argmin(list1)
    4

In [67]:
# try it here
list1 = [1,3,2,6,0,2,3,4,5]
argmax(list1)

3

>**(b)** **(extra)** Instead of just finding the index of the largest or smallest element, one might be interested in the entire list of indices that would sort the list. In one of the previous exercises we presented you with this piece of code for finding the indices that sort a list.


In [78]:
l = [1,3,2,6,0,2,3,4,5]
list(zip(*sorted(zip(l, range(len(l))))))[1]

(4, 0, 2, 5, 1, 6, 7, 8, 3)

>It works by combining the list with the list of indices, sorting the combined list, and then untangling the results. Have a look at the documentation of the *zip* function to understand how it works. Write a function:

In [79]:
def argsort(l):
  sorted_idx = []
  idx_and_item = []
  for i, v in enumerate(l):
    idx_and_item.append((v, i))
  for v, i in sorted(idx_and_item):
    sorted_idx.append(i)
  return sorted_idx

>that returns the list of indices that would sort the list, but instead of using the hard to read
line above that uses zip, use list comprehensions. Example output:

    >>> l = [1,3,2,6,0,2,3,4,5]
    >>> argsort(l)
    [4, 0, 2, 5, 1, 6, 7, 8, 3]
    >>> [l[i] for i in argsort(l)]
    [0, 1, 2, 2, 3, 3, 4, 5, 6]


In [80]:
# try it here
l = [1,3,2,6,0,2,3,4,5]
print(argsort(l))
print([l[i] for i in argsort(l)])

[4, 0, 2, 5, 1, 6, 7, 8, 3]
[0, 1, 2, 2, 3, 3, 4, 5, 6]


### Problem 5. Simple ciphers


Suppose you wish to send your friend a message, and if someone happens to look at it, you do not want them to know what it says.<br>
A simple way of doing this is to replace each letter, with
a different one.<br>
For example, suppose I wish to send the phrase “dancing is silent poetry”.<br>
By exchanging each letter with another, we can encode this as: “robqwbu wg gwzsbh dcshfm”.

>**(a)** Write a function that swaps the letter in a string according to a dictionary. For example:


In [81]:
def swapdict(string, dic):
  swapped = ''
  for c in string:
    if c in dic:
      swapped += dic[c]
    else:
      swapped += c
  return swapped

    >>> print swapdict('hello', {'e': 'i'})
    hillo
    >>> print swapdict('hello', {'l': 'w'})
    hewwo
    >>> print swapdict('hello', {'l': 'm', 'h': 'p', 'e': 'o', 'o': 'e'})
    pomme

In [82]:
# your code here
print(swapdict('hello', {'e': 'i'}))

hillo


>**(b)** Write a function that generates a dictionary whose keys are letters of the alphabet, and whose values are those letters shifted along by a given number of letters.


In [86]:
def shiftdict(i):

  import string
  alphabet = string.ascii_lowercase

  shiftdict = {}
  for c in alphabet:
    shifted = ord(c) + i
    if shifted < ord('a'):
      shifted = ord('z') - (ord('a') - shifted) + 1
    elif shifted > ord('z'):
      shifted = ord('a') + (shifted - ord('z')) - 1
    shiftdict[c] = chr(shifted)
  return shiftdict

In [88]:
print(shiftdict(0))

{'a': 'a', 'b': 'b', 'c': 'c', 'd': 'd', 'e': 'e', 'f': 'f', 'g': 'g', 'h': 'h', 'i': 'i', 'j': 'j', 'k': 'k', 'l': 'l', 'm': 'm', 'n': 'n', 'o': 'o', 'p': 'p', 'q': 'q', 'r': 'r', 's': 's', 't': 't', 'u': 'u', 'v': 'v', 'w': 'w', 'x': 'x', 'y': 'y', 'z': 'z'}


    >>> print shiftdict(0)
    {'a': 'a', 'b': 'b', ..., 'z': 'z'}
    >>> print shiftdict(3)
    {'a': 'd', 'b': 'e', ..., 'z': 'c'}
    >>> print shiftdict(13)
    {'a': 'n', 'b': 'o', ..., 'z': 'm'}

>In the first case, the letters are not shifted, because the argument to *shiftdict* is zero. In the second case, letters are shifted along by three letters: “a” is the first letter, and “d” is the forth letter, and so key “a” points to letter “d”.

In [89]:
# try it here
print(shiftdict(3))

{'a': 'd', 'b': 'e', 'c': 'f', 'd': 'g', 'e': 'h', 'f': 'i', 'g': 'j', 'h': 'k', 'i': 'l', 'j': 'm', 'k': 'n', 'l': 'o', 'm': 'p', 'n': 'q', 'o': 'r', 'p': 's', 'q': 't', 'r': 'u', 's': 'v', 't': 'w', 'u': 'x', 'v': 'y', 'w': 'z', 'x': 'a', 'y': 'b', 'z': 'c'}


>**(c)** Now we are ready to encode our message: “dancing is silent poetry”.


    >>> print swapdict('dancing is silent poetry', shiftdict(14))

In [92]:
# your code here
swapdict("dancing is silent poetry", shiftdict(14)) #  “robqwbu wg gwzsbh dcshfm”

'robqwbu wg gwzsbh dcshfm'

>Check that it matches the encoding given above.


>**(d)** Write a function that takes a dictionary and swaps the roles of the keys and the values.


In [93]:
def invertdict(dictionary):
  return dict((v, k) for k, v in dictionary.items())

Here are some examples to check it works:

    >>> invertdict({'a':'b'})
    {'b': 'a'}
    >>> invertdict({'b':'a', 'a': 'b'})
    {'a': 'b', 'b': 'a'}
    >>> invertdict({'a':'b', 'b': 'c', 'c': 'a'})
    {'a': 'c', 'b': 'a','c': 'b'}

In [94]:
# your code here
invertdict({'a':'b'})

{'b': 'a'}

>**(e)** Can you decode this message, that was encoded using the same scheme? “qzuipo nblft ju tjnqmf ipqfgvmmz”. Use only *invertdict*, *swapdict* and *shiftdict*.


In [96]:
# your code here
print(swapdict('qzuipo nblft ju tjnqmf ipqfgvmmz', shiftdict(25)))

python makes it simple hopefully


>**(f)** You notice that your friend is sending encrypted messages to other people, but they appear to be encoded using a different argument to shiftdict.<br>
Use a for-loop, swapdict and shiftdict to work out the encoding scheme, and what this message says: “nyhcpaf pz aol yvva vm spnoaulzz”.


In [101]:
# your code here
for i in range(27):
  print(swapdict('nyhcpaf pz aol yvva vm spnoaulzz', shiftdict(i)))

print("\n")
print('i = 19, ' , swapdict('nyhcpaf pz aol yvva vm spnoaulzz', shiftdict(19)))

nyhcpaf pz aol yvva vm spnoaulzz
ozidqbg qa bpm zwwb wn tqopbvmaa
pajerch rb cqn axxc xo urpqcwnbb
qbkfsdi sc dro byyd yp vsqrdxocc
rclgtej td esp czze zq wtrseypdd
sdmhufk ue ftq daaf ar xustfzqee
tenivgl vf gur ebbg bs yvtugarff
ufojwhm wg hvs fcch ct zwuvhbsgg
vgpkxin xh iwt gddi du axvwicthh
whqlyjo yi jxu heej ev bywxjduii
xirmzkp zj kyv iffk fw czxykevjj
yjsnalq ak lzw jggl gx dayzlfwkk
zktobmr bl max khhm hy ebzamgxll
alupcns cm nby liin iz fcabnhymm
bmvqdot dn ocz mjjo ja gdbcoiznn
cnwrepu eo pda nkkp kb hecdpjaoo
doxsfqv fp qeb ollq lc ifdeqkbpp
epytgrw gq rfc pmmr md jgefrlcqq
fqzuhsx hr sgd qnns ne khfgsmdrr
gravity is the root of lightness
hsbwjuz jt uif sppu pg mjhiuoftt
itcxkva ku vjg tqqv qh nkijvpguu
judylwb lv wkh urrw ri oljkwqhvv
kvezmxc mw xli vssx sj pmklxriww
lwfanyd nx ymj wtty tk qnlmysjxx
mxgboze oy znk xuuz ul romnztkyy
nyhcpaf pz aol yvva vm spnoaulzz


i = 19,  gravity is the root of lightness
